
package unit8_ooplibrary;

/**
 *
 * @author namphan
 */
public class LibraryGUI extends javax.swing.JFrame {

    /**
     * Creates new form LibraryGUI
     */
    public LibraryGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libraryTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookTab = new javax.swing.JPanel();
        bookCover = new javax.swing.JPanel();
        book1 = new javax.swing.JButton();
        book2 = new javax.swing.JButton();
        book3 = new javax.swing.JButton();
        bookInfo = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cdTab = new javax.swing.JPanel();
        cdCover = new javax.swing.JPanel();
        audio1 = new javax.swing.JButton();
        audio2 = new javax.swing.JButton();
        audio3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cdInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        libraryTab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        libraryTab.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Oriya MN", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("G1 LIBRARY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 292, 59);

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("WE HOPE YOU CAN FIND SOME LITTLE INTERESTING THINGS HERE.");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 500, 420, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/global.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 80, 419, 348);

        libraryTab.addTab("HOME", new javax.swing.ImageIcon(getClass().getResource("/Image/HomeButton.png")), jPanel1); // NOI18N

        bookTab.setBackground(new java.awt.Color(255, 204, 204));
        bookTab.setLayout(null);

        javax.swing.GroupLayout bookCoverLayout = new javax.swing.GroupLayout(bookCover);
        bookCover.setLayout(bookCoverLayout);
        bookCoverLayout.setHorizontalGroup(
            bookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        bookCoverLayout.setVerticalGroup(
            bookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        bookTab.add(bookCover);
        bookCover.setBounds(200, 230, 290, 282);

        book1.setText("book1");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        bookTab.add(book1);
        book1.setBounds(20, 29, 163, 97);

        book2.setText("book 2");
        book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book2ActionPerformed(evt);
            }
        });
        bookTab.add(book2);
        book2.setBounds(20, 215, 163, 97);

        book3.setText("book 3");
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });
        bookTab.add(book3);
        book3.setBounds(20, 382, 163, 96);

        jTextArea1.setBackground(new java.awt.Color(255, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        bookInfo.setViewportView(jTextArea1);

        bookTab.add(bookInfo);
        bookInfo.setBounds(200, 10, 290, 210);

        libraryTab.addTab("BOOK", new javax.swing.ImageIcon(getClass().getResource("/Image/book.png")), bookTab); // NOI18N

        cdTab.setBackground(new java.awt.Color(153, 255, 153));
        cdTab.setLayout(null);

        javax.swing.GroupLayout cdCoverLayout = new javax.swing.GroupLayout(cdCover);
        cdCover.setLayout(cdCoverLayout);
        cdCoverLayout.setHorizontalGroup(
            cdCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        cdCoverLayout.setVerticalGroup(
            cdCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        cdTab.add(cdCover);
        cdCover.setBounds(200, 239, 290, 280);

        audio1.setText("audio1");
        audio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audio1ActionPerformed(evt);
            }
        });
        cdTab.add(audio1);
        audio1.setBounds(6, 34, 177, 94);

        audio2.setText("audio2");
        audio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audio2ActionPerformed(evt);
            }
        });
        cdTab.add(audio2);
        audio2.setBounds(6, 208, 177, 94);

        audio3.setText("video 3");
        audio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audio3ActionPerformed(evt);
            }
        });
        cdTab.add(audio3);
        audio3.setBounds(6, 364, 177, 94);

        cdInfo.setBackground(new java.awt.Color(153, 255, 153));
        cdInfo.setColumns(20);
        cdInfo.setRows(5);
        jScrollPane2.setViewportView(cdInfo);

        cdTab.add(jScrollPane2);
        jScrollPane2.setBounds(200, 10, 290, 210);

        libraryTab.addTab("CD-DVD", new javax.swing.ImageIcon(getClass().getResource("/Image/cd.png")), cdTab); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libraryTab, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(libraryTab, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// book tab
    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book1ActionPerformed

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book3ActionPerformed

    private void book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book2ActionPerformed
// cd-dvd tab
    private void audio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audio1ActionPerformed

    private void audio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audio2ActionPerformed

    private void audio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audio3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audio1;
    private javax.swing.JButton audio2;
    private javax.swing.JButton audio3;
    private javax.swing.JButton book1;
    private javax.swing.JButton book2;
    private javax.swing.JButton book3;
    private javax.swing.JPanel bookCover;
    private javax.swing.JScrollPane bookInfo;
    private javax.swing.JPanel bookTab;
    private javax.swing.JPanel cdCover;
    private javax.swing.JTextArea cdInfo;
    private javax.swing.JPanel cdTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTabbedPane libraryTab;
    // End of variables declaration//GEN-END:variables
}
